### PR TITLE
removing max line length

### PR DESCRIPTION
**Pull request by ste00martin**
Whats your thoughts? Since VS Code has pretty good auto line wrap I'm not as huge into line lengths

### CODE REVIEW

**Comment by cazzer** [comment]
Why would you ever need a line longer than 80 characters?

**Comment by ste00martin** [comment]
Here's why:
```
export function registerScreens(store, Provider) {
  Navigation.registerComponent('volta.BackButton', () => BackButton, store, Provider)
  Navigation.registerComponent('volta.ChangePassword', () => ChangePassword, store, Provider)
  Navigation.registerComponent('volta.ChooseLogin', () => ChooseLogin, store, Provider)
  Navigation.registerComponent('volta.Drawer', () => Drawer, store, Provider)
  Navigation.registerComponent('volta.FAQ', () => FAQ, store, Provider)
  Navigation.registerComponent('volta.ForgotPassword', () => ForgotPassword, store, Provider)
  Navigation.registerComponent('volta.ForgotPasswordConfirm', () => ForgotPasswordConfirm, store, Provider)
  Navigation.registerComponent('volta.LoadingScreen', () => LoadingScreen, store, Provider)
  Navigation.registerComponent('volta.Login', () => Login, store, Provider)
  Navigation.registerComponent('volta.Map', () => Map, store, Provider)
  Navigation.registerComponent('volta.MapHeader', () => MapHeader, store, Provider)
  Navigation.registerComponent('volta.Notification', () => Notification, store, Provider)
  Navigation.registerComponent('volta.Onboarding', () => Onboarding, store, Provider)
  Navigation.registerComponent('volta.Profile', () => Profile, store, Provider)
  Navigation.registerComponent('volta.Registration', () => Registration, store, Provider)
  Navigation.registerComponent('volta.RegistrationConfirm', () => RegistrationConfirm, store, Provider)
  Navigation.registerComponent('volta.Report', () => Report, store, Provider)
  Navigation.registerComponent('volta.Settings', () => Settings, store, Provider)
  Navigation.registerComponent('volta.VehicleDetail', () => VehicleDetail, store, Provider)
}
```

I'd rather have imports or long lists of declarations on single lines

**Comment by cazzer** [comment]
Is this an edge case or a common case? If it's common I'm all for removing the rule, but in Node and React land lines that long are generally edge and a good use for `/* eslint-disable */`

**Comment by jsuna** [comment]
I'm with @cazzer with this one, I feel it's more declarative to handle edge cases in the code

**Pull request closed without merging**
